import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, realpath, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { chromium } from 'playwright';
import { initializeProject } from '../src/files.mjs';
import { startEditor } from '../src/app.mjs';

test('one-page layout choice preserves content, images and visual style while exporting one page', async t => {
  const outer = await mkdtemp(path.join(tmpdir(), 'tech-resume-one-page-choice-'));
  const directory = path.join(outer, 'data');
  await initializeProject(directory, 'campus');
  const app = await startEditor(directory);
  const initial = await app.project.read();
  const layout = structuredClone(initial.layout);
  Object.assign(layout, { theme: 'forest-rail', fontFamily: 'serif', density: 'standard', bodyPt: 11, lineHeight: 1.2 });
  Object.assign(layout.page, { maxPages: 2, marginMm: 15, marginHorizontalMm: 18 });
  Object.assign(layout.spacing, { sectionMm: 4, entryMm: 4 });
  Object.assign(layout.header, { align: 'spread', contactStyle: 'icons' });
  await app.project.save({ ...initial, layout });
  const before = await app.project.read();
  const browser = await chromium.launch({ channel: 'chromium' });
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  t.after(async () => {
    await browser.close(); await app.close();
    const actual = await realpath(outer);
    assert.ok(actual.startsWith(path.join(await realpath(tmpdir()), 'tech-resume-one-page-choice-')));
    await rm(actual, { recursive: true, force: true });
  });
  await page.goto(app.url);
  await page.locator('#settings-open').click();
  await page.getByRole('button', { name: '试用紧凑单页' }).click();
  await page.locator('#save-status').filter({ hasText: '已自动保存' }).waitFor({ timeout: 60000 });
  const after = await app.project.read();
  assert.equal(after.source, before.source);
  assert.deepEqual(after.front.assets, before.front.assets);
  assert.equal(after.layout.theme, before.layout.theme);
  assert.equal(after.layout.fontFamily, before.layout.fontFamily);
  assert.deepEqual(after.layout.header, before.layout.header);
  assert.deepEqual(after.layout.images, before.layout.images);
  assert.equal(after.layout.density, 'compact');
  assert.equal(after.layout.bodyPt, 10);
  assert.equal(after.layout.lineHeight, 1.5);
  assert.deepEqual(after.layout.spacing, { sectionMm: 3, entryMm: 3 });
  assert.equal(after.layout.page.marginMm, 9);
  assert.equal(after.layout.page.marginHorizontalMm, undefined);
  assert.equal(after.layout.page.maxPages, 1);
  assert.equal(await page.locator('#dense-one-page').getAttribute('aria-pressed'), 'true');
  const preview = await app.project.preview();
  assert.equal(preview.metrics.pageCount, 1);
  assert.equal(preview.metrics.images.length, 2);
  assert.deepEqual(preview.metrics.networkRequests, []);
  await page.reload();
  await page.locator('#settings-open').click();
  assert.equal(await page.locator('#dense-one-page').getAttribute('aria-pressed'), 'true');
  await page.locator('#body-size').selectOption('10.25');
  assert.equal(await page.locator('#dense-one-page').getAttribute('aria-pressed'), 'false');
  await page.setViewportSize({ width: 390, height: 820 });
  await page.locator('[data-settings-target="settings-spacing"]').click();
  await page.locator('#dense-one-page').scrollIntoViewIfNeeded();
  const bounds = await page.locator('#dense-one-page').boundingBox();
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
});
