import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, realpath, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { chromium } from 'playwright';
import { startEditor } from '../src/app.mjs';
import { initializeProject } from '../src/files.mjs';

test('web layout controls save locally and change the actual PDF without changing resume text', async t => {
  const outer = await mkdtemp(path.join(tmpdir(), 'tech-resume-layout-ui-'));
  const directory = path.join(outer, 'data');
  await initializeProject(directory, 'campus');
  const app = await startEditor(directory);
  const browser = await chromium.launch({ channel: 'chromium' });
  const page = await browser.newPage({ viewport: { width: 1400, height: 950 } });
  const external = [];
  await page.route('**/*', route => {
    if (new URL(route.request().url()).hostname !== '127.0.0.1') { external.push(route.request().url()); return route.abort(); }
    return route.continue();
  });
  t.after(async () => {
    await browser.close(); await app.close();
    const actual = await realpath(outer);
    assert.ok(actual.startsWith(path.join(await realpath(tmpdir()), 'tech-resume-layout-ui-')));
    await rm(actual, { recursive: true, force: true });
  });
  await page.goto(app.url);
  await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  const source = (await app.project.read()).source;
  await page.locator('#settings-open').click();
  assert.equal(await page.locator('[data-accent="#3478f6"]').evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(52, 120, 246)');
  await page.locator('[data-settings-target="settings-spacing"]').click();
  assert.equal(await page.locator('#advanced-layout').evaluate(element => element.open), true);
  await page.locator('#density').selectOption('compact');
  await page.locator('#font-family').selectOption('serif');
  await page.locator('#body-size').selectOption('9.75');
  await page.locator('#header-align').selectOption('spread');
  await page.locator('#contact-style').selectOption('icons');
  await page.locator('#portrait-slot').selectOption('end');
  await page.locator('#portrait-size').selectOption('21', { timeout: 3000 });
  await page.locator('#schoolLogo-size').selectOption('16', { timeout: 3000 });
  await page.locator('#margin-horizontal').selectOption('9');
  await page.locator('#margin-top').selectOption('10');
  await page.locator('#margin-bottom').selectOption('8');
  await page.locator('#section-spacing').selectOption('1.4');
  await page.locator('#entry-spacing').selectOption('1.5');
  await page.locator('[data-accent="#3478f6"]').click();
  await page.locator('#save-status').filter({ hasText: '已自动保存' }).waitFor({ timeout: 30000 });
  const state = await app.project.read();
  assert.equal(state.source, source);
  assert.equal(state.layout.density, 'compact');
  assert.equal(state.layout.fontFamily, 'serif');
  assert.equal(state.layout.bodyPt, 9.75);
  assert.equal(state.layout.header.align, 'spread');
  assert.equal(state.layout.header.contactStyle, 'icons');
  assert.equal(state.layout.images.portrait.slot, 'end');
  assert.equal(state.layout.images.portrait.widthMm, 21);
  assert.ok(Math.abs(state.layout.images.portrait.heightMm / 21 - 31 / 23) < 0.001);
  assert.equal(state.layout.images.schoolLogo.widthMm, 16);
  assert.equal(state.layout.page.marginHorizontalMm, 9);
  assert.equal(state.layout.page.marginTopMm, 10);
  assert.equal(state.layout.page.marginBottomMm, 8);
  assert.equal(state.layout.spacing.sectionMm, 1.4);
  assert.equal(state.layout.spacing.entryMm, 1.5);
  assert.equal(state.layout.accent, '#3478f6');
  await page.getByRole('button', { name: '关闭设置' }).click();
  await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  const preview = await app.project.preview();
  assert.equal(preview.metrics.pageCount, 1);
  assert.equal(preview.metrics.outOfBounds.length, 0);
  assert.ok(Math.abs(preview.metrics.images.find(image => image.asset === 'schoolLogo').width - 16 * 96 / 25.4) < 1);
  await page.reload();
  await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  await page.locator('#settings-open').click();
  assert.equal(await page.locator('#density').inputValue(), 'compact');
  assert.equal(await page.locator('#margin-horizontal').inputValue(), '9');
  await page.setViewportSize({ width: 390, height: 820 });
  await page.locator('[data-settings-target="settings-spacing"]').click();
  await page.locator('#margin-bottom').scrollIntoViewIfNeeded();
  const marginBounds = await page.locator('#margin-bottom').boundingBox();
  assert.ok(marginBounds.x >= 0 && marginBounds.x + marginBounds.width <= 390);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(external, []);
});
