import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile, mkdir, realpath, rm } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { chromium } from 'playwright';
import { startEditor } from '../src/app.mjs';
import { initializeProject } from '../src/files.mjs';
import { kitRoot } from '../src/render.mjs';
import { decodeLibraryBackup } from '../src/library-backup.mjs';
import { pdfExpectations } from '../scripts/pdf-expectations.mjs';

test('browser recovers trashed resumes, reviews and restores a full library and downloads the original library to undo it', async t => {
  const outer = await mkdtemp(path.join(tmpdir(), 'tech-resume-library-ui-')), root = path.join(outer, '完整库');
  await initializeProject(root, 'campus'); let app = await startEditor(root);
  const browser = await chromium.launch({ channel: 'chromium' }), page = await browser.newPage({ viewport: { width: 1500, height: 1040 } });
  t.after(async () => { await browser.close(); await app.close(); const actual = await realpath(outer); assert.ok(actual.startsWith(path.join(await realpath(tmpdir()), 'tech-resume-library-ui-'))); await rm(actual, { recursive: true, force: true, maxRetries: 5 }); });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const qa = path.join(kitRoot, 'tmp/pdfs/library-management'); await mkdir(qa, { recursive: true });
  const ready = () => page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  const original = await app.project.read(); await page.goto(app.url); await ready();
  await page.locator('#library-open').click(); assert.equal(await page.locator('#resume-trash').isDisabled(), true);
  await page.getByRole('button', { name: '关闭简历库管理' }).click();
  await page.locator('#resume-copy').click(); await page.locator('#resume-name').fill('校招副本'); await page.locator('#resume-submit').click();
  await page.locator('#resume-dialog').waitFor({ state: 'hidden' }); await ready(); const copied = await app.project.read();
  await page.locator('#library-open').click(); await page.locator('#resume-trash').click(); await page.locator('#resume-trash-cancel').click();
  assert.equal((await app.project.read()).resumes.length, 2);
  await page.locator('#resume-trash').click(); await page.locator('#resume-trash-confirm').click(); await page.locator('#resume-trash-dialog').waitFor({ state: 'hidden' });
  await page.locator(`[data-trash-id="${copied.resumeId}"]`).waitFor();
  await page.locator(`[data-trash-id="${copied.resumeId}"] button`).click(); await page.locator('#trash-restore-name').fill('已找回校招副本'); await page.locator('#trash-restore-confirm').click();
  await page.locator('#trash-restore-dialog').waitFor({ state: 'hidden' }); assert.equal((await app.project.read()).trash.length, 0);
  await page.getByRole('button', { name: '关闭简历库管理' }).click(); await page.locator('#resume-select').selectOption(copied.resumeId); await ready();
  await page.locator('#library-open').click(); await page.locator('#resume-trash').click(); await page.locator('#resume-trash-confirm').click(); await page.locator('#resume-trash-dialog').waitFor({ state: 'hidden' });
  const [download] = await Promise.all([page.waitForEvent('download'), page.locator('#library-export').click()]);
  const zipFile = path.join(outer, '整库.zip'); await download.saveAs(zipFile); const archive = await readFile(zipFile), decoded = decodeLibraryBackup(archive);
  assert.equal(decoded.catalog.resumes.length, 1); assert.equal(decoded.trash.resumes.length, 1);
  await page.getByRole('button', { name: '关闭简历库管理' }).click(); await page.locator('#resume-create').click(); await page.locator('#resume-name').fill('恢复前新增简历'); await page.locator('#resume-submit').click();
  await page.locator('#resume-dialog').waitFor({ state: 'hidden' }); await ready(); const beforeRestore = await app.project.read();
  await page.locator('#library-open').click();
  await page.locator('#library-import').setInputFiles({ name: '损坏.zip', mimeType: 'application/zip', buffer: Buffer.from('bad ZIP') });
  await page.locator('#library-error:not([hidden])').waitFor(); assert.equal((await app.project.read()).resumeId, beforeRestore.resumeId);
  await page.locator('#library-import').setInputFiles(zipFile); await page.locator('#library-restore-dialog[open]').waitFor();
  assert.match(await page.locator('#library-restore-summary').textContent(), /1 份在用简历、1 份回收站/);
  await page.screenshot({ path: path.join(qa, 'restore-review.png') }); await page.locator('#library-restore-cancel').click();
  assert.equal((await app.project.read()).resumeId, beforeRestore.resumeId);
  await page.locator('#library-import').setInputFiles(zipFile); await page.locator('#library-restore-dialog[open]').waitFor(); await page.locator('#library-restore-confirm').click();
  await page.locator('#library-restore-dialog').waitFor({ state: 'hidden' }); await ready();
  const restored = await app.project.read(); assert.equal(restored.resumeId, original.resumeId); assert.equal(restored.source, original.source); assert.equal(restored.trash[0].id, copied.resumeId);
  const [undoDownload] = await Promise.all([page.waitForEvent('download'), page.locator('#library-before-download').click()]);
  const undoFile = path.join(outer, '恢复前整库.zip'); await undoDownload.saveAs(undoFile);
  assert.equal(decodeLibraryBackup(await readFile(undoFile)).catalog.activeId, beforeRestore.resumeId);
  await page.locator('#toast').waitFor({ state: 'hidden' }); await page.screenshot({ path: path.join(qa, 'library-dialog.png') });
  await page.setViewportSize({ width: 980, height: 640 });
  await page.locator('#library-export').scrollIntoViewIfNeeded();
  const close = await page.getByRole('button', { name: '关闭简历库管理' }).boundingBox(); assert.ok(close.y >= 0 && close.y + close.height <= 640);
  await page.screenshot({ path: path.join(qa, 'library-small-window.png') }); await page.setViewportSize({ width: 1500, height: 1040 });
  await page.getByRole('button', { name: '关闭简历库管理' }).click();
  const result = await app.project.preview(); assert.equal(result.metrics.pageCount, 1); assert.equal(result.metrics.images.length, 2);
  await writeFile(path.join(qa, 'restored-campus.pdf'), result.buffer); await writeFile(path.join(qa, 'restored-campus.expected.json'), JSON.stringify(pdfExpectations({ ...result, images: Object.fromEntries(result.metrics.images.map(item => [item.asset, true])) }, 1)));
  await app.close(); app = await startEditor(root); await page.goto(app.url); await ready();
  assert.equal((await app.project.read()).trash.length, 1); await page.locator('#library-open').click(); await page.locator('#library-import').setInputFiles(undoFile);
  await page.locator('#library-restore-dialog[open]').waitFor(); await page.locator('#library-restore-confirm').click(); await page.locator('#library-restore-dialog').waitFor({ state: 'hidden' }); await ready();
  const undone = await app.project.read(); assert.equal(undone.resumeId, beforeRestore.resumeId); assert.equal(undone.source, beforeRestore.source); assert.equal(undone.resumes.length, 2); assert.deepEqual(errors, []);
});
