import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, realpath } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { chromium } from 'playwright';
import { startEditor } from '../src/app.mjs';
import { kitRoot } from '../src/render.mjs';

test('real visual previews work offline on desktop and mobile; styles are independent of content and persist without replacing it', async t => {
  const outer = await mkdtemp(path.join(tmpdir(), 'tech-resume-theme-ui-')), directory = path.join(outer, 'data');
  let app = await startEditor(directory);
  const browser = await chromium.launch({ channel: 'chromium' }), page = await browser.newPage({ viewport: { width: 1480, height: 1120 } });
  const errors = [], external = []; page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', route => { if (!['127.0.0.1','localhost'].includes(new URL(route.request().url()).hostname)) { external.push(route.request().url()); return route.abort(); } return route.continue(); });
  t.after(async () => { await browser.close(); await app.close(); const actual = await realpath(outer); assert.ok(actual.startsWith(path.join(await realpath(tmpdir()), 'tech-resume-theme-ui-'))); await rm(actual, { recursive: true, force: true, maxRetries: 3 }); });
  const qa = path.join(kitRoot, 'tmp/pdfs/themes'); await mkdir(qa, { recursive: true });
  await page.goto(app.url); await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  await page.locator('#start-choose').click();
  assert.equal(await page.locator('input[name=start-theme]').count(), 6);
  assert.equal(await page.locator('#start-content option').count(), 10);
  await page.waitForFunction(() => [...document.querySelectorAll('.theme-options img')].length === 6 && [...document.querySelectorAll('.theme-options img')].every(img => img.complete && img.naturalWidth === 380));
  await page.screenshot({ path: path.join(qa, 'gallery-desktop.png') });
  await page.setViewportSize({ width: 390, height: 820 }); await page.screenshot({ path: path.join(qa, 'gallery-mobile.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.locator('#start-theme-warm-labels').check(); await page.locator('#start-content').selectOption('java-backend');
  await page.locator('#start-submit').click(); await page.locator('#start-dialog').waitFor({ state: 'hidden' });
  await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  let state = await app.project.read(); assert.equal(state.layout.theme, 'warm-labels'); assert.match(state.front.person.target, /Java/);
  let source = state.source; const originalId = state.resumeId;
  await page.setViewportSize({ width: 1480, height: 1120 });
  await page.locator('#settings-open').click(); await page.locator('#visual-theme').selectOption('forest-rail');
  await page.locator('#save-status').filter({ hasText: '已自动保存' }).waitFor();
  state = await app.project.read(); assert.equal(state.layout.theme, 'forest-rail'); assert.equal(state.source, source);
  await page.getByRole('button', { name: '关闭设置' }).click();
  await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  assert.equal(await page.locator('#template option:not([disabled])').count(), 10);
  await page.locator('#template').selectOption('frontend'); await page.locator('#replace-confirm').click();
  await page.locator('#replace-dialog').waitFor({ state: 'hidden' });
  await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  state = await app.project.read(); assert.equal(state.layout.theme, 'forest-rail'); assert.match(state.front.person.target, /前端/); source = state.source;
  await page.locator('#resume-create').click(); await page.locator('#resume-template').selectOption('data-analyst');
  await page.locator('#resume-theme').selectOption('minimal-mono'); await page.locator('#resume-name').fill('独立黑白版');
  await page.locator('#resume-submit').click(); await page.locator('#resume-dialog').waitFor({ state: 'hidden' });
  await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  assert.equal((await app.project.read()).layout.theme, 'minimal-mono');
  await page.locator('#resume-select').selectOption(originalId); await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  await app.close(); app = await startEditor(directory); await page.goto(app.url);
  await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  state = await app.project.read(); assert.equal(state.layout.theme, 'forest-rail'); assert.equal(state.source, source);
  assert.deepEqual(errors, []); assert.deepEqual(external, []);
});
