import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, realpath, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { chromium } from 'playwright';
import { initializeProject } from '../src/files.mjs';
import { startEditor } from '../src/app.mjs';
import { kitRoot } from '../src/render.mjs';
import { pdfExpectations } from '../scripts/pdf-expectations.mjs';

test('each resume can reorder its sections and restore a preset without rewriting the Markdown or losing images', async t => {
  const outer = await mkdtemp(path.join(tmpdir(), 'tech-resume-order-ui-')), directory = path.join(outer, '分栏 简历');
  await initializeProject(directory, 'campus'); const app = await startEditor(directory);
  const browser = await chromium.launch({ channel: 'chromium' }), page = await browser.newPage({ viewport: { width: 1500, height: 1050 } });
  const errors = [], remote = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', route => {
    if (new URL(route.request().url()).hostname !== '127.0.0.1') { remote.push(route.request().url()); return route.abort(); }
    return route.continue();
  });
  t.after(async () => {
    await browser.close(); await app.close(); const actual = await realpath(outer);
    assert.ok(actual.startsWith(path.join(await realpath(tmpdir()), 'tech-resume-order-ui-')));
    await rm(actual, { recursive: true, force: true, maxRetries: 3 });
  });
  const original = await app.project.read(), source = await readFile(path.join(directory, 'resume.md'));
  const images = Object.fromEntries(await Promise.all(Object.entries(original.front.assets).map(async ([key, asset]) => [key, await readFile(path.join(directory, asset.src))])));
  await page.goto(app.url); await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  await page.locator('#settings-open').click();
  const rows = page.locator('#order-list .order-row');
  await page.waitForFunction(() => document.querySelectorAll('#order-list .order-row').length === 5);
  assert.deepEqual(await rows.evaluateAll(elements => elements.map(element => element.dataset.sectionId)), ['education', 'skills', 'internship', 'projects', 'additional']);
  assert.equal(await rows.first().locator('[data-action=up]').isDisabled(), true);
  await rows.filter({ hasText: '教育背景' }).locator('[data-action=down]').click();
  await page.waitForFunction(() => document.querySelector('#order-list .order-row')?.dataset.sectionId === 'skills');
  assert.equal(await rows.filter({ hasText: '教育背景' }).locator('[data-action=down]').evaluate(button => button === document.activeElement), true);
  await page.locator('#save-status').filter({ hasText: '已自动保存' }).waitFor();
  const changed = await app.project.read();
  assert.deepEqual(changed.layout.sectionOrder, ['skills', 'education', 'internship', 'projects', 'additional']);
  assert.deepEqual(await readFile(path.join(directory, 'resume.md')), source);
  for (const [key, asset] of Object.entries(changed.front.assets)) assert.deepEqual(await readFile(path.join(directory, asset.src)), images[key]);
  const preview = await app.project.preview();
  assert.equal(preview.metrics.pageCount, 1); assert.deepEqual(preview.layout.sectionOrder, changed.layout.sectionOrder);
  assert.equal(preview.metrics.images.length, 2);
  const qa = path.join(kitRoot, 'tmp/pdfs/section-order'); await mkdir(qa, { recursive: true });
  await writeFile(path.join(qa, 'reordered-campus.pdf'), preview.buffer);
  await writeFile(path.join(qa, 'reordered-campus.expected.json'), JSON.stringify(pdfExpectations({ ...preview, images: { portrait: true, schoolLogo: true } }, 1)));
  await page.setViewportSize({ width: 390, height: 760 });
  await page.screenshot({ path: path.join(qa, 'small-order-dialog.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  const resetBounds = await page.locator('#order-reset').boundingBox(); assert.ok(resetBounds.x >= 0 && resetBounds.x + resetBounds.width <= 390);
  await page.locator('#schoolLogo-file').scrollIntoViewIfNeeded();
  const logoBounds = await page.locator('#schoolLogo-file').boundingBox(); assert.ok(logoBounds.y >= 0 && logoBounds.y + logoBounds.height <= 760);
  const closeBounds = await page.getByRole('button', { name: '关闭设置' }).boundingBox(); assert.ok(closeBounds.y >= 0 && closeBounds.y + closeBounds.height <= 760);
  await page.screenshot({ path: path.join(qa, 'small-order-images.png') });
  await page.getByRole('button', { name: '关闭设置' }).click();
  await page.reload(); await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  await page.locator('#settings-open').click(); await page.waitForFunction(() => document.querySelector('#order-list .order-row')?.dataset.sectionId === 'skills');
  await page.getByRole('button', { name: '关闭设置' }).click();

  await page.locator('#resume-create').click(); await page.locator('#resume-name').fill('第二份申请');
  await page.locator('#resume-template').selectOption('campus'); await page.locator('#resume-submit').click();
  await page.locator('#resume-dialog').waitFor({ state: 'hidden' }); await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  await page.locator('#settings-open').click(); await page.waitForFunction(() => document.querySelector('#order-list .order-row')?.dataset.sectionId === 'education');
  await page.getByRole('button', { name: '关闭设置' }).click();
  await page.locator('#resume-select').selectOption(original.resumeId);
  await page.waitForFunction(id => document.querySelector('#resume-select').value === id, original.resumeId);
  await page.locator('#settings-open').click(); await page.waitForFunction(() => document.querySelector('#order-list .order-row')?.dataset.sectionId === 'skills');
  await page.locator('#order-reset').click(); await page.waitForFunction(() => document.querySelector('#order-list .order-row')?.dataset.sectionId === 'education');
  await page.locator('#save-status').filter({ hasText: '已自动保存' }).waitFor();
  assert.equal((await app.project.read()).layout.sectionOrder, undefined);
  await page.locator('#preset').selectOption('experience');
  await page.waitForFunction(() => document.querySelectorAll('#order-list .order-row').length === 5 && document.querySelector('#order-list .order-row')?.dataset.sectionId === 'skills');
  assert.deepEqual(await rows.evaluateAll(elements => elements.map(element => element.dataset.sectionId)), ['skills', 'internship', 'projects', 'education', 'additional']);
  assert.equal((await app.project.read()).layout.sectionOrder, undefined);
  assert.deepEqual(await readFile(path.join(directory, 'resume.md')), source);
  await page.locator('#max-pages').selectOption('2');
  await rows.filter({ hasText: '教育背景' }).locator('[data-action=rename]').click();
  await page.locator('#section-title-dialog[open]').waitFor();
  const titleBounds = await page.locator('#section-title').boundingBox(); assert.ok(titleBounds.x >= 0 && titleBounds.x + titleBounds.width <= 390);
  await page.screenshot({ path: path.join(qa, 'small-section-title.png') });
  await page.locator('#section-title').fill('求学经历'); await page.locator('#section-title-submit').click();
  await page.locator('#section-title-dialog').waitFor({ state: 'hidden' });
  await rows.filter({ hasText: '求学经历' }).waitFor();
  const renamedSource = source.toString('utf8').replace('## 教育背景 {#education .entries}', '## 求学经历 {#education .entries}');
  assert.equal(await readFile(path.join(directory, 'resume.md'), 'utf8'), renamedSource);
  assert.equal((await app.project.read()).layout.sectionOrder, undefined);
  assert.equal((await app.project.read()).layout.page.maxPages, 2);
  for (const [key, asset] of Object.entries((await app.project.read()).front.assets)) assert.deepEqual(await readFile(path.join(directory, asset.src)), images[key]);
  const renamedPreview = await app.project.preview(); assert.equal(renamedPreview.metrics.pageCount, 1);
  assert.deepEqual(renamedPreview.document.sections.map(section => section.id), preview.document.sections.map(section => section.id));
  await writeFile(path.join(qa, 'renamed-campus.pdf'), renamedPreview.buffer);
  await writeFile(path.join(qa, 'renamed-campus.expected.json'), JSON.stringify(pdfExpectations({ ...renamedPreview, images: { portrait: true, schoolLogo: true } }, 1)));
  await page.reload(); await page.locator('#pdf-download:not([disabled])').waitFor({ timeout: 30000 });
  await page.locator('#settings-open').click(); await rows.filter({ hasText: '求学经历' }).waitFor();
  await rows.filter({ hasText: '求学经历' }).locator('[data-action=rename]').click();
  await page.locator('#section-title').fill(' '); await page.locator('#section-title-submit').click();
  await page.locator('#section-title-error:not([hidden])').waitFor();
  assert.match(await page.locator('#section-title-error').innerText(), /章节名称/);
  assert.equal(await readFile(path.join(directory, 'resume.md'), 'utf8'), renamedSource);
  await page.getByRole('button', { name: '关闭章节改名' }).click();
  await assert.rejects(app.project.renameSectionTitle({ resumeId: original.resumeId, revision: original.revision, sectionId: 'education', title: '旧窗口覆盖' }), error => error.code === 'CONFLICT');
  assert.deepEqual(errors, []); assert.deepEqual(remote, []);
});
