import assert from 'node:assert/strict';
import { spawn, execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, mkdir, readFile, writeFile, rm, realpath, copyFile } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { PDFDocument } from 'pdf-lib';
import { pdfExpectations } from './pdf-expectations.mjs';
import { initializeProject } from '../src/files.mjs';
import { extractPackage } from '../src/updates.mjs';
import { chromium } from 'playwright';
const exec = promisify(execFile), root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
assert.equal(process.platform, 'win32');
const version = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8')).version;
const outside = await realpath(await mkdtemp(path.join(tmpdir(), 'tech-resume-免安装 验证-')));
let child, url, token, browser;
try {
  await exec(process.env.TECH_RESUME_PYTHON || 'python', ['-c', 'import sys,zipfile; z=zipfile.ZipFile(sys.argv[1]); assert all(".." not in n.split("/") and not n.startswith("/") for n in z.namelist()); z.extractall(sys.argv[2])', path.join(root, 'tmp/packages', `tech-resume-windows-x64-${version}.zip`), outside], { windowsHide: true, timeout: 120000 });
  const portable = path.join(outside, `tech-resume-windows-x64-${version}`), executable = path.join(portable, '启动简历.exe');
  const settingsFile = path.join(outside, '用户 设置/settings.json'), directory = path.join(outside, '用户 设置/data');
  const args = ['--no-open', '--settings', settingsFile];
  await initializeProject(path.join(portable, 'my-resume'), 'blank');
  const legacySource = await readFile(path.join(portable, 'my-resume/resume.md'));
  const system = process.env.SystemRoot || 'C:\\Windows';
  child = spawn(executable, args, { cwd: outside, windowsHide: true, stdio: 'ignore', env: { ...process.env, PATH: path.join(system, 'System32'), PLAYWRIGHT_BROWSERS_PATH: path.join(outside, 'missing-browser-cache'), HTTP_PROXY: 'http://127.0.0.1:9', HTTPS_PROXY: 'http://127.0.0.1:9' } });
  const sessionFile = path.join(directory, 'app-session.local.json');
  let session;
  for (let i = 0; i < 100; i++) {
    try { session = JSON.parse(await readFile(sessionFile, 'utf8')); break; } catch {}
    if (child.exitCode !== null) throw new Error('Portable launcher exited before startup');
    await new Promise(resolve => setTimeout(resolve, 200));
  }
  assert.ok(session, 'Portable app did not start'); url = session.url;
  assert.deepEqual(await readFile(path.join(portable, 'my-resume/resume.md')), legacySource);
  assert.equal(JSON.parse(await readFile(settingsFile, 'utf8')).dataDirectory, directory);
  const actualRuntime = await exec(path.join(system, 'System32/WindowsPowerShell/v1.0/powershell.exe'), ['-NoProfile', '-Command', `[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new($false); (Get-CimInstance Win32_Process -Filter 'ProcessId = ${Number(session.pid)}').ExecutablePath`], { windowsHide: true });
  assert.equal(actualRuntime.stdout.trim().toLowerCase(), path.join(portable, 'runtime/node.exe').toLowerCase());
  const alternate = path.join(outside, '另一程序目录'); await mkdir(alternate); await copyFile(executable, path.join(alternate, '启动简历.exe'));
  const second = spawn(path.join(alternate, '启动简历.exe'), args, { cwd: outside, windowsHide: true, stdio: 'ignore' });
  assert.equal(await new Promise(resolve => second.once('exit', resolve)), 0);
  assert.equal(JSON.parse(await readFile(sessionFile, 'utf8')).pid, session.pid);
  const html = await (await fetch(url)).text(); token = /name="resume-token" content="([a-f0-9]+)"/.exec(html)[1];
  const post = async (endpoint, body) => {
    const response = await fetch(url + endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: url.slice(0, -1), 'X-Resume-Token': token }, body: JSON.stringify(body) });
    const result = await response.json(); assert.equal(response.status, 200, JSON.stringify(result)); return result;
  };
  let state = await (await fetch(url + 'api/state')).json();
  const preview = await (await fetch(url + 'api/preview')).json(); assert.equal(preview.pageCount, 1);
  state.front.person.name = '免安装填写示例';
  state = await post('api/save', { resumeId: state.resumeId, revision: state.revision, front: state.front, body: state.body, layout: state.layout });
  browser = await chromium.launch({ executablePath: path.join(portable, 'runtime/browsers/chromium_headless_shell-1243/chrome-headless-shell-win64/chrome-headless-shell.exe'), headless: true });
  const page = await browser.newPage({ viewport: { width: 1400, height: 980 } }), remoteRequests = [];
  page.on('request', request => { if (/^https?:/.test(request.url()) && new URL(request.url()).origin !== new URL(url).origin) remoteRequests.push(request.url()); });
  await page.goto(url); const viewer = page.frameLocator('#pdf-frame');
  await viewer.locator('.pdf-page[data-page="1"][data-rendered="true"]').waitFor({ timeout: 30000 });
  assert.match(await viewer.locator('.textLayer').innerText(), /免安装填写示例/);
  await page.locator('#entry-manager-summary').click();
  const entry = page.locator('[data-section-id=projects] .entry-row').first();
  await entry.locator('[data-action=edit]').click(); await page.locator('#entry-title').fill('免安装项目示例');
  await page.locator('#entry-submit').click(); await page.locator('#entry-dialog').waitFor({ state: 'hidden' });
  await viewer.locator('.textLayer').filter({ hasText: '免安装项目示例' }).waitFor({ timeout: 30000 });
  assert.match(await viewer.locator('.textLayer').innerText(), /免安装项目示例/);
  state = await (await fetch(url + 'api/state')).json();
  const document = await fetch(url + `document.pdf?revision=${state.revision}&download=1`); assert.equal(document.status, 200);
  const buffer = Buffer.from(await document.arrayBuffer()); assert.equal((await PDFDocument.load(buffer)).getPageCount(), 1);
  const qa = path.join(root, 'tmp/pdfs/editor'); await mkdir(qa, { recursive: true });
  await writeFile(path.join(qa, 'portable-blank.pdf'), buffer);
  const { parseResume } = await import('../src/input.mjs'); const { resolveSectionOrder } = await import('../src/schema.mjs');
  const model = parseResume(state.source).document; state.layout.sectionOrder = resolveSectionOrder(model, state.layout);
  await writeFile(path.join(qa, 'portable-blank.expected.json'), JSON.stringify(pdfExpectations({ document: model, layout: state.layout, images: {} }, 1)));
  state = await post('api/template', { resumeId: state.resumeId, template: 'experience', revision: state.revision });
  const twoPages = await (await fetch(url + 'api/preview')).json(); assert.equal(twoPages.pageCount, 2);
  await page.reload(); await viewer.locator('.pdf-page[data-page="2"][data-rendered="true"]').waitFor({ timeout: 30000 });
  assert.deepEqual(remoteRequests, []); await browser.close(); browser = null;
  assert.match(await readFile(path.join(directory, 'resume.md'), 'utf8'), /后端/);
  const originalId = state.resumeId;
  const snapshot = await post('api/backup', { resumeId: state.resumeId, revision: state.revision });
  const archive = await fetch(url + `backup.zip?resumeId=${state.resumeId}&backupId=${snapshot.id}`);
  assert.equal(archive.status, 200);
  state = await post('api/resumes/duplicate', { resumeId: state.resumeId, revision: state.revision, name: '另一份求职版本' });
  assert.notEqual(state.resumeId, originalId);
  const otherId = state.resumeId;
  state = await post('api/resumes/trash', { resumeId: state.resumeId, revision: state.revision, libraryRevision: state.libraryRevision });
  assert.equal(state.resumeId, originalId); assert.equal(state.trash[0].id, otherId);
  const libraryZip = await fetch(url + `library.zip?${new URLSearchParams({ resumeId: state.resumeId, revision: state.revision, libraryRevision: state.libraryRevision })}`);
  assert.equal(libraryZip.status, 200); const libraryBytes = Buffer.from(await libraryZip.arrayBuffer());
  const raw = async endpoint => {
    const response = await fetch(url + endpoint, { method: 'POST', headers: { Origin: url.slice(0, -1), 'X-Resume-Token': token, 'X-Resume-Id': state.resumeId, 'X-Resume-Revision': state.revision }, body: libraryBytes });
    const result = await response.json(); assert.equal(response.status, 200, JSON.stringify(result)); return result;
  };
  const reviewed = await raw('api/library/inspect'); assert.equal(reviewed.resumeCount, 1); assert.equal(reviewed.trashCount, 1);
  state = await post('api/resumes/restore-trash', { resumeId: state.resumeId, revision: state.revision, libraryRevision: state.libraryRevision, targetId: otherId, name: '另一份求职版本' });
  state = await raw(`api/library/restore-upload?${new URLSearchParams({ libraryRevision: state.libraryRevision, sha256: reviewed.sha256 })}`);
  assert.equal(state.resumes.length, 1); assert.equal(state.trash[0].id, otherId);
  const prior = await fetch(url + `library-before-restore.zip?backupId=${state.libraryBackupBeforeRestore.backupId}`); assert.equal(prior.status, 200);
  state = await post('api/resumes/restore-trash', { resumeId: state.resumeId, revision: state.revision, libraryRevision: state.libraryRevision, targetId: otherId, name: '另一份求职版本' });
  state = await post('api/resumes/switch', { resumeId: state.resumeId, revision: state.revision, targetId: otherId });
  state.front.person.name = '第二份简历';
  state = await post('api/save', { resumeId: state.resumeId, revision: state.revision, front: state.front, body: state.body, layout: state.layout });
  state = await post('api/resumes/switch', { resumeId: state.resumeId, revision: state.revision, targetId: originalId });
  assert.notEqual(state.front.person.name, '第二份简历');
  state = await post('api/resumes/switch', { resumeId: state.resumeId, revision: state.revision, targetId: otherId });
  assert.equal(state.front.person.name, '第二份简历');
  state = await post('api/restore', { resumeId: state.resumeId, revision: state.revision, backupId: (await (await fetch(url + `api/history?resumeId=${otherId}`)).json()).backups.find(b => b.kind === 'initial').id });
  assert.notEqual(state.front.person.name, '第二份简历');
  await post('api/exit', {});
  if (child.exitCode === null) await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('Portable shutdown timed out')), 10000); child.once('exit', code => { clearTimeout(timer); assert.equal(code, 0); resolve(); }); });
  const replacement = await extractPackage(path.join(root, 'tmp/packages', `tech-resume-windows-x64-${version}.zip`), path.join(outside, '新版暂存'), version);
  child = spawn(path.join(replacement, '启动简历.exe'), args, { cwd: outside, windowsHide: true, stdio: 'ignore', env: { ...process.env, PATH: path.join(system, 'System32'), PLAYWRIGHT_BROWSERS_PATH: path.join(outside, 'missing-browser-cache'), HTTP_PROXY: 'http://127.0.0.1:9', HTTPS_PROXY: 'http://127.0.0.1:9' } });
  let restarted;
  for (let i = 0; i < 100; i++) { try { restarted = JSON.parse(await readFile(sessionFile, 'utf8')); if (restarted.pid !== session.pid) break; } catch {} await new Promise(resolve => setTimeout(resolve, 200)); }
  assert.ok(restarted && restarted.pid !== session.pid, 'Restart did not create a fresh session');
  url = restarted.url; token = /name="resume-token" content="([a-f0-9]+)"/.exec(await (await fetch(url)).text())[1];
  const afterRestart = await (await fetch(url + 'api/state')).json();
  assert.equal(afterRestart.resumeId, otherId); assert.equal(afterRestart.resumes.length, 2); assert.notEqual(afterRestart.front.person.name, '第二份简历');
  await post('api/exit', {});
  if (child.exitCode === null) await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('Restart shutdown timed out')), 10000); child.once('exit', code => { clearTimeout(timer); assert.equal(code, 0); resolve(); }); });
  child = spawn(path.join(alternate, '启动简历.exe'), [...args, '--wait', '--update-from', replacement], { cwd: outside, windowsHide: true, stdio: 'ignore' });
  assert.equal(await new Promise(resolve => child.once('exit', resolve)), 1, 'Broken new version must report failure');
  let fallback;
  for (let i = 0; i < 100; i++) { try { fallback = JSON.parse(await readFile(sessionFile, 'utf8')); if (fallback.pid !== restarted.pid) break; } catch {} await new Promise(resolve => setTimeout(resolve, 200)); }
  assert.ok(fallback && fallback.pid !== restarted.pid, 'Failed update did not reopen the previous program');
  url = fallback.url; token = /name="resume-token" content="([a-f0-9]+)"/.exec(await (await fetch(url)).text())[1];
  assert.equal((await (await fetch(url + 'api/state')).json()).resumeId, otherId);
  await post('api/exit', {});
  for (let i = 0; i < 50; i++) { try { await readFile(sessionFile); } catch (error) { if (error.code === 'ENOENT') break; throw error; } await new Promise(resolve => setTimeout(resolve, 100)); }
  await writeFile(path.join(root, 'tmp/packages/windows-smoke.json'), JSON.stringify({ version, bundledNode: true, noNodeInPath: true, independentBrowserCache: true, offlineProxy: true, singletonAcrossProgramDirectories: true, autosave: true, pdfPages: [1, 2], offlineCanvasPreview: true, selectablePreviewText: true, noRemotePreviewRequests: true, multipleResumes: true, recycleBin: true, wholeLibraryZip: true, wholeLibraryRestore: true, completeBackup: true, restore: true, restartPersistence: true, separateDataDirectory: true, legacyMigration: true, verifiedUpdateExtraction: true, versionSwitchPersistence: true, startupFailureFallback: true, cleanExit: true }, null, 2));
  console.log('Windows EXE passed: offline export, complete library migration, separate data, cross-version singleton, verified extraction, version switch and failed-start fallback.');
} finally {
  await browser?.close();
  if (url && token) await fetch(url + 'api/exit', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: url.slice(0, -1), 'X-Resume-Token': token }, body: '{}', signal: AbortSignal.timeout(3000) }).catch(() => {});
  if (child?.pid && child.exitCode === null) await exec('taskkill', ['/PID', String(child.pid), '/T', '/F'], { windowsHide: true }).catch(() => {});
  const actual = await realpath(outside); assert.ok(actual.startsWith(path.join(await realpath(tmpdir()), 'tech-resume-免安装 验证-')));
  await rm(actual, { recursive: true, force: true, maxRetries: 5, retryDelay: 500 });
}
